// <auto-generated />
using CineMontecasteloMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineMontecasteloMvc.Migrations
{
    [DbContext(typeof(CineContext))]
    [Migration("20251124165741_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineMontecasteloMvc.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FotoMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2024,
                            Descripcion = "Las emociones vuelven con nuevas aventuras.",
                            Duracion = 110,
                            Genero = "Animación",
                            Precio = 9.50m,
                            Titulo = "Inside Out 2"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2024,
                            Descripcion = "Paul Atreides y los Fremen en Arrakis.",
                            Duracion = 165,
                            Genero = "Ciencia ficción",
                            Precio = 9.00m,
                            Titulo = "Dune:Parte Dos"
                        });
                });

            modelBuilder.Entity("CineMontecasteloMvc.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aforo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aforo = 150,
                            Nombre = "Sala 1",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aforo = 100,
                            Nombre = "Sala 2",
                            PeliculaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Aforo = 80,
                            Nombre = "Sala 3"
                        });
                });

            modelBuilder.Entity("CineMontecasteloMvc.Models.Sala", b =>
                {
                    b.HasOne("CineMontecasteloMvc.Models.Pelicula", "Pelicula")
                        .WithMany("Salas")
                        .HasForeignKey("PeliculaId");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("CineMontecasteloMvc.Models.Pelicula", b =>
                {
                    b.Navigation("Salas");
                });
#pragma warning restore 612, 618
        }
    }
}
